### ISSUE TITLE
When updating point content as curator, rollback occurs if status is set to anything other than "pending"

### ISSUE THREAD

**Issue by madoleary** [tosdr/phoenix#717] opened 2018-09-14 06:54 UTC
I imagine that in the server logs, this throws an error. If "pending" is the required status for a point after it's updated, then there should not be a drop-down menu that allows the user to select from any of the other statuses.

**Comment by michielbdejong** [comment] 2018-09-14 07:44
Duplicate of #710. right?

**Comment by Photon-GitHub** [comment] 2018-09-18 14:30
You should still be able to set a point to declined, especially when reviewing points from the backlog.

**Comment by michielbdejong** [comment] 2018-09-24 09:27
> add a case to point set a "change requested"

What do you mean to say? As the author of the point, you can set that point to pending, draft or declined. But for curators, the dropdown also offers other statuses, including 'changes-requested'. It makes no sense to request changes for a point where you yourself are the author, so that option should be removed from the dropdown.

**Closed** 2018-09-24 09:56 UTC
